### ISSUE TITLE
Mutliple survey pages (24553)

### ISSUE THREAD

**Issue by MaiklT** [DNNCommunity/DNN.Survey#11]
## Is your feature request related to a problem?
**Feature**
This is a copy of Issue 24553 form CodePlex.

> **Mutliples survey by name**
> Hi, Is it a way to add (if i dont see it) a name field to have more than 1 survey in the db.
> For exemple :
> - Page 1 : Question about the services you want add into my catalog
> - Page 2 : Question about customer satisfaction
> Regards
> Mike

## Describe the solution you'd like
Structure a survey into multiple pages with headers for each page

## Describe alternatives you've considered
Could be as well on one page, but add headers for different sections. Sections could be displayed in panels for better clarity.

**Comment by valadas** [comment]
Merged
