### ISSUE TITLE
Add Dropdown-List answers (14463, 14465)

### ISSUE THREAD

**Issue by MaiklT** [DNNCommunity/DNN.Survey#12]
## Is your feature request related to a problem?
**Feature**
This is a copy of issue 14463 ad 14465 form CodePlex.

> **Add Option Display Types**
> Add Drop down menu and Rating Scale option types

and

> **Combo Box Options**
> Provide a feature to display single response options in a combo box versus a series of radio buttons.

## Describe the solution you'd like
Add an additional answer type "Single choice (Dropdown list)"

## Describe alternatives you've considered
Consider also adding a Dropdownlist with multiple options.

**Comment by valadas** [comment]
Merged
