### ISSUE TITLE
Sort Results (14464 )

### ISSUE THREAD

**Issue by MaiklT** [DNNCommunity/DNN.Survey#13]
## Is your feature request related to a problem?
**Feature**
This is a copy of Issue 14464 form CodePlex.

> **Sort results when displayed**
> For simple dichotomous yes/no responses, 'view results' ordering is not a big issue; however, as you add more and more options/responses to each question, the results can get a bit ugly when not sorted in, say, descending order. The ability to apply sorting to the 'view results' display would add tremendous value to this project.

## Describe the solution you'd like
Add an option to the question if results should be displayed by view order, alphabetically or number of votes.

**Comment by valadas** [comment]
Merged
