### ISSUE TITLE
CSV Export: Add setting for separator and delimiter

### ISSUE THREAD

**Issue by MaiklT** [DNNCommunity/DNN.Survey#14]
## Is your feature request related to a problem?
**Feature**
Add a setting for the separator and delimiter characters for the CSV export. In former versions this was always a comma and no delimiter, but that does not work when opening the CSV file in Excel (at least not in the German version?). It has been replaced by a semicolon and no delimiter in version 9.0.0, but maybe it's better to introduce a setting.

## Describe the solution you'd like
Add two settings: Separator and Delimiter. Maybe it is better to provide options in a dropdownlist.

## Describe alternatives you've considered
Maybe also add a setting for the encoding (ANSI or UTF-8)

**Comment by valadas** [comment]
@MaiklT I see you PR took care of all the issues except this one, is this correct or is this also part of it but you forgot to mention the issue number in the pr ?

**Comment by MaiklT** [comment]
@valadas: no, it is just an idea for a future release. I did not want to add new features before this version is released.

**Comment by valadas** [comment]
Will be included in upcoming 9.1.0
