### ISSUE TITLE
Archive of surveys (14462)

### ISSUE THREAD

**Issue by MaiklT** [DNNCommunity/DNN.Survey#15]
## Is your feature request related to a problem?
**Feature**
This is a copy of Issue 14462 form CodePlex.

> **Previous Polls list and display**
> Visitors can click through to "Previous Polls/Surveys", where they can view a list of the expired surveys by name and click on them to view their final results. An example of such a list can be viewed here: [http://www.monster.co.uk/polls/](http://www.monster.co.uk/polls/)

## Describe the solution you'd like
This could be a different module that archives old surveys.

## Additional context
We have to think if this could be an option for a free module. The feature sounds more like something used for professional polls...

**Comment by valadas** [comment]
Merged
