### ISSUE TITLE
Survey results layout is askew (25051)

### ISSUE THREAD

**Issue by MaiklT** [DNNCommunity/DNN.Survey#17]
## Describe the bug
This is a copy of Issue 25051 form CodePlex.

> **Survey layout is askew**
> In DNN 7+ the width and height of survey color bars is equal (eg the height and width of color blocks is the same) and the resulting layout looks terrible. This is enhanced by the inability to set the width of results, as reported in other issues.

![6659](https://user-images.githubusercontent.com/7458140/55238689-6a334500-5235-11e9-801f-8e29de118c56.png)

**Comment by valadas** [comment]
Merged
