### ISSUE TITLE
User cannot vote after results are cleared (16565/21105/24551)

### ISSUE THREAD

**Issue by MaiklT** [DNNCommunity/DNN.Survey#18]
## Is your feature request related to a problem?
**Feature**
This is a copy of Issue 16565, 21105 and 24551 form CodePlex.

> **Cannot clear survey results with 1 Vote/Reg user**
> If I have 1 vote/registered user selected, and I use the Clear Results Data function (Clear)... it clears the results in the survey, but the user cannot vote again on the cleared survey. 
> Sometimes we like to change 1 question; or test the survey module... then the "test" user cannot vote.
> SUMMARY: If the survey results are cleared, the user voting history should also be cleared.

**Comment by valadas** [comment]
Merged
