### ISSUE TITLE
"Show closing date message" and "Add consent checkbox?" check boxes are not saved correctly when the values are changed from checked to unchecked

### ISSUE THREAD

**Issue by Marker4** [DNNCommunity/DNN.Survey#39]
## Describe the bug
Module - Survey Settings Tab - "Show closing date message" and "Add consent checkbox?" check boxes are not saved correctly when the values are changed from checked to unchecked.

## Software Versions
- DNN: 09.00.00
- Module: 09.00.00

## To Reproduce
1. Go to Module Settings - Survey Settings Tab.
2. Check both "Show closing date message" and "Add consent checkbox?" 
3. Update the Module
4. Go to Module Settings - Survey Settings Tab.
5. Uncheck both "Show closing date message" and "Add consent checkbox?" 
6. Update the Module
7. See that the module still displays both items as if they were checked.

## Expected behavior
Items should uncheck.

## Solution:
Edit the file Settings.ascx.cs in the Project. Go to line 204. Replace TabModuleId with ModuleId as such:
ModuleController.Instance.DeleteModuleSetting(ModuleId, settingName);

**Comment by MaiklT** [comment]
Thank you for pointing this out. I could reproduce that behaviour and will fix it in the next version.

As a workaround I can provide the following SQL Scripts that you can use in Settings :: SQL Console:

(to find the ModuleID):

    SELECT
       m.ModuleID,
       tm.ModuleTitle,
       t.TabName,
       t.TabPath
    FROM
       {databaseOwner}{objectQualifier}Modules m
       INNER JOIN {databaseOwner}{objectQualifier}ModuleDefinitions md ON md.ModuleDefID = m.ModuleDefID
       INNER JOIN {databaseOwner}{objectQualifier}TabModules tm ON tm.ModuleID = m.ModuleID
       INNER JOIN {databaseOwner}{objectQualifier}Tabs t ON t.TabID = tm.TabID
    WHERE
       md.DefinitionName = 'Survey'

(to set "Show closing date message" off - replace XYZ with the ModuleID):

    DELETE FROM {databaseOwner}{objectQualifier}ModuleSettings
    WHERE ModuleID = XYZ AND SettingName = 'ShowClosingDateMessage'

(to set "Add consent checkbox?" off - replace XYZ with the ModuleID):

    DELETE FROM {databaseOwner}{objectQualifier}ModuleSettings
    WHERE ModuleID = XYZ AND SettingName = 'PrivacyConfirmation'

Please restart the application pool after you ran any of those two scripts (under Settings :: Server, click the "Restart Application" button on the top, or recycle the application pool in IIS manager).

When you still see the message and/or the consent checkbox refresh the page - it should be gone.
