### ISSUE TITLE
Die Eingabezeichenfolge hat das falsche Format

### ISSUE THREAD

**Issue by rthoeni** [DNNCommunity/DNN.Survey#46]
## Describe the bug
Fehler: ist zur Zeit nicht verfügbar. Die Eingabezeichenfolge hat das falsche Format
Error: is currently not available. The input string is in the wrong format

## Software Versions
- DNN: 9.5.0
- Module: 9.0.1
- Chart.js v2.7.3/2.9.2

## To Reproduce
1. add Question (wie ist das Wetter)
2. Click on '3 answer "geht so>Add answer" "naja>Add answer" und "mal schauen>Add answer"'
3. Scroll down to 'save'
Fehler: ist zur Zeit nicht verfügbar. DotNetNuke.Services.Exceptions.ModuleLoadException: Die Eingabezeichenfolge hat das falsche Format. ---> System.FormatException: Die Eingabezeichenfolge hat das falsche Format. bei System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal) bei System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info) bei DNN.Modules.Survey.SurveyEdit.UpdateButton_Click(Object sender, EventArgs e) --- Ende der internen Ausnahmestapelüberwachung ---

-----------------
ModuleId:546
ModuleDefId:139
FriendlyName:
ModuleControlSource:DesktopModules/Survey/SurveyEdit.ascx
AbsoluteURL:/Default.aspx
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:be0016de-76d9-4798-92c8-ce3064a00032
AssemblyVersion:9.5.0
PortalId:0
UserId:1
TabId:68
RawUrl:/links/test/ctl/edit/mid/546?popUp=true
Referrer:https://www.xyz.ch/links/test/ctl/edit/mid/546?popUp=true
UserAgent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15
ExceptionHash:Dyl3xZuvr1yaNbnRzC+hpPQtdlY=
Message:Die Eingabezeichenfolge hat das falsche Format.
StackTrace:
InnerMessage:Die Eingabezeichenfolge hat das falsche Format.
InnerStackTrace:
   bei System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   bei System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   bei DNN.Modules.Survey.SurveyEdit.UpdateButton_Click(Object sender, EventArgs e)
Source:
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:
Server Name: vps74

**Comment by MaiklT** [comment]
Cannot reproduce. See [screenshot](https://www.dropbox.com/s/zs6zs9w90gi55ie/Anmerkung%202020-05-02%20112034.png?dl=0)
Have you installed the DotNet 4.7.2 framework?

**Comment by rthoeni** [comment]
I have now uninstalled it, restarted the server and reinstalled it.. now it's working..crazy
ASP.net 4.8, SRV 2016, SQL 2014
The DNN basic installation is in German and has a Let's Encrypt certificate.

Addendum:
DNN 9.6.0 (Fresh-install) is error-free. 
DNN 9.5.0 2020-05-02 13:03:33.084+02:00 [vps74][D:12][T:105][ERROR] DotNetNuke.Services.Exceptions.Exceptions - FriendlyMessage="Fehler:  ist zur Zeit nicht verf�gbar." ctrl="ASP.desktopmodules_survey_surveyedit_ascx" exc="System.FormatException: Die Eingabezeichenfolge hat das falsche Format.
   bei System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   bei System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   bei DNN.Modules.Survey.SurveyEdit.UpdateButton_Click(Object sender, EventArgs e)"

<img width="970" alt="Bildschirmfoto 2020-05-02 um 13 15 07" src="https://user-images.githubusercontent.com/12658708/80862674-3e279600-8c77-11ea-80b2-b7ee36adb0b9.png">

add answer, save > Error

**Comment by rthoeni** [comment]
Sorry, I'm going to open it again
New Installation DNN 9.6.0, the modul works fine....
<img width="687" alt="Bildschirmfoto 2020-05-06 um 21 49 10" src="https://user-images.githubusercontent.com/12658708/81222487-a3b3b380-8fe4-11ea-85df-0bc59cf03090.png">

my DNN 9.5.0 is going crazy. I can't choose anything here (example above)
<img width="683" alt="Bildschirmfoto 2020-05-06 um 21 49 30" src="https://user-images.githubusercontent.com/12658708/81222683-f42b1100-8fe4-11ea-9a58-3bd6e540dbef.png">

Does somebody has any idea?

2020-05-06 22:11:14.714+02:00 [vps74][D:13][T:47][ERROR] DotNetNuke.Services.Exceptions.Exceptions - System.OperationCanceledException: Der Vorgang wurde abgebrochen.
   bei System.Threading.CancellationToken.ThrowOperationCanceledException()
   bei System.Net.Http.HttpContentExtensions.<ReadAsAsyncCore>d__0`1.MoveNext()
--- Ende der Stapel�berwachung vom vorhergehenden Ort, an dem die Ausnahme ausgel�st wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Web.Http.ModelBinding.FormatterParameterBinding.<ExecuteBindingAsyncCore>d__0.MoveNext()
--- Ende der Stapel�berwachung vom vorhergehenden Ort, an dem die Ausnahme ausgel�st wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__24.MoveNext()
--- Ende der Stapel�berwachung vom vorhergehenden Ort, an dem die Ausnahme ausgel�st wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Web.Http.Controllers.HttpActionBinding.<ExecuteBindingAsyncCore>d__0.MoveNext()
--- Ende der Stapel�berwachung vom vorhergehenden Ort, an dem die Ausnahme ausgel�st wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__24.MoveNext()
--- Ende der Stapel�berwachung vom vorhergehenden Ort, an dem die Ausnahme ausgel�st wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- Ende der Stapel�berwachung vom vorhergehenden Ort, an dem die Ausnahme ausgel�st wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- Ende der Stapel�berwachung vom vorhergehenden Ort, an dem die Ausnahme ausgel�st wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()

**Comment by valadas** [comment]
Do you have any interesting logs in portals/_default/logs maybe

**Comment by MaiklT** [comment]
Roland, are you able to reproduce this behaviour with the new release (version 9.1.0)? Or did you find a solution (as I am not sure if this is related to the module, there were no other reports about this).

**Comment by rthoeni** [comment]
Maikl, i have try now with a new/fresh DNN 9.7.2 CE/Survey9.1.0 an become this error again:

Modul shows:
 Fehler: ist zur Zeit nicht verfügbar. DotNetNuke.Services.Exceptions.ModuleLoadException: Die Eingabezeichenfolge hat das falsche Format. ---> System.FormatException: Die Eingabezeichenfolge hat das falsche Format. bei System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal) bei System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info) bei System.Convert.ToInt32(String value) bei DNN.Modules.Survey.SurveyEdit.UpdateButton_Click(Object sender, EventArgs e) --- Ende der internen Ausnahmestapelüberwachung --- 

Log shows:
2020-11-09 11:29:57.125+01:00 [vps74][D:5][T:39][ERROR] DotNetNuke.Services.Exceptions.Exceptions - FriendlyMessage="Fehler:  ist zur Zeit nicht verf�gbar." ctrl="ASP.desktopmodules_survey_surveyedit_ascx" exc="System.FormatException: Die Eingabezeichenfolge hat das falsche Format.

   bei System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)

   bei System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)

   bei System.Convert.ToInt32(String value)

   bei DNN.Modules.Survey.SurveyEdit.UpdateButton_Click(Object sender, EventArgs e)"

Eventlog shows:
ModuleId:399

ModuleDefId:125

FriendlyName:

ModuleControlSource:DesktopModules/Survey/SurveyEdit.ascx

AbsoluteURL:/Default.aspx

DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke

ExceptionGUID:45bf0f09-7de4-4404-8b57-e766149db004

AssemblyVersion:9.7.2

PortalId:0

UserId:1

TabId:35

RawUrl:/intern/ctl/edit/mid/399?popUp=true

Referrer:

UserAgent:Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:82.0) Gecko/20100101 Firefox/82.0

ExceptionHash:k2OcJ0aGXyxk3YIIxxQCx7BsNVk=

Message:Die Eingabezeichenfolge hat das falsche Format.

StackTrace:

InnerMessage:Die Eingabezeichenfolge hat das falsche Format.

InnerStackTrace:

   bei System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   bei System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   bei System.Convert.ToInt32(String value)
   bei DNN.Modules.Survey.SurveyEdit.UpdateButton_Click(Object sender, EventArgs e)

Source:

FileName:

FileLineNumber:0

FileColumnNumber:0

Method:

Server Name: vps74

**Comment by rthoeni** [comment]
*New information and hope it helps you*
New module inserted, create survey (here question 1), type, direction and diagram can be selected, answer (here test 1) written
<img width="482" alt="Bild_1" src="https://user-images.githubusercontent.com/12658708/98535657-c3bf7a80-2286-11eb-8fb6-29129b339ecb.PNG">

As soon as I add the answer, the Type, Direction, and Diagram fields disappear
<img width="548" alt="Bild_2" src="https://user-images.githubusercontent.com/12658708/98535750-ef426500-2286-11eb-836d-f055af367b45.PNG">

**Comment by MaiklT** [comment]
Thank you Roland, I never seen this before. I'll try to reproduce.

**Comment by MaiklT** [comment]
Roland, I just tried this, it works as expected. Maybe a problem with your skin or do you use a jQuery CDN (jQuery versions conflict)? Could you please try to use the standard skin (Xcillion) and a Xcillion container for the module? Or are you using the default skin and containers?

**Comment by rthoeni** [comment]
I think I found the bug. but I'm not sure yet....
As soon as the `<httpErrors>` are set, this message appears.
I have now done the whole thing with a new installation of DNN 9.5.0 (Is the last working version where the German language can be installed)directly to 9.8.0.
That's how it goes now.
I have now done everything again step by step according to your instructions (dnnwerk.at) and tested the survey every time until I found it.
Sorry for my English.
>> As soon as I have installed the 40 FINGERS SEO REDIRECT and set up the httpErrors as described, it no longer works...
`<httpErrors>             <remove statusCode="404" subStatusCode="-1" />             <error statusCode="404" prefixLanguageFilePath="" path="/404" responseMode="ExecuteURL" />         </httpErrors>`

I tried the following:
`<httpErrors>
            <remove statusCode="500" subStatusCode="-1" />
            <remove statusCode="403" subStatusCode="-1" />
            <remove statusCode="404" subStatusCode="-1" />
            <remove statusCode="401" subStatusCode="-1" />
            <error statusCode="401" prefixLanguageFilePath="" path="/401" responseMode="ExecuteURL" />
            <error statusCode="404" prefixLanguageFilePath="" path="/404" responseMode="ExecuteURL" />
            <error statusCode="403" prefixLanguageFilePath="" path="/403" responseMode="ExecuteURL" />
            <error statusCode="500" prefixLanguageFilePath="" path="/500" responseMode="ExecuteURL" />
        </httpErrors>`
