### ISSUE TITLE
Charts don't display when a double quote was entered in a free text response

### ISSUE THREAD

**Issue by MaiklT** [DNNCommunity/DNN.Survey#48]
## Describe the bug
When a double quote is entered in a free text response, the Javascript to display the chart fails.

## Software Versions
- DNN: xx.xx.xx
- Module: 09.00.01

## To Reproduce
1. Add a free trext response to a survey
2. Add answers, use a double quote somewhere in the free text response
3. Show results
4. No charts are displayed

## Expected behavior
Charts should display.

## Error log
Javascript console:
Uncaught SyntaxError: Unexpected identifier

## Additional context
Workaround: replace the double quotes in the database by single quotes

**Comment by MaiklT** [comment]
Same for line breaks.

**Comment by valadas** [comment]
Fixed in shortly upcoming 9.1.0
