### ISSUE TITLE
Probleem styling results view

### ISSUE THREAD

**Issue by wbonekamp** [DNNCommunity/DNN.Survey#50]
## Describe the bug
In the latest version 09.00.01 the result component is changed to ChartJS.
Unfortunately this component is pretty static and you can't change the Look and Feel.

In context of the WCAG we need the optimize/change the result graph.

Is there a way to change this with css/template?

## Software Versions
- DNN: 9.6.x
- Module: 09.00.01

## To Reproduce
1. Add the survey module on a page
2. Add the questions/results
3. Fill in the survey
4. Click on "View Results"
5. Show the Graph

## Expected behavior
Results with block graphs like in the old module.
Option to style/change the resultgraph with css/template/?
Option to make the resultsgraph wcag compatible

## Screenshots
This is the resultsview we like to have:
![image](https://user-images.githubusercontent.com/7567981/94124723-a577f980-fe55-11ea-8378-af12c573607a.png)

**Comment by MaiklT** [comment]
We won't implement things like this, but you can always download the results as a CSV file and use any reporting tool (MS Access, Excel, Crystal, ...) to get the styling you want. And you can also implement it and make a pull request.
