### ISSUE TITLE
Add labels for explanations etc.

### ISSUE THREAD

**Issue by MaiklT** [DNNCommunity/DNN.Survey#6]
## Describe the solution you'd like
It should be possible to add labels etc. to provide further information to a question or something alike.

**Comment by valadas** [comment]
Hey @MaiklT I am closing the issues manually that where included in your PR. When you write closes #something, it automatically closes the issue but only the issue right after the word closes, so...

closes #something, #somethingelse, #yetanotherthing only catches the first one. Next time, please put them one per line with the word closes on each. Thanks.
