### ISSUE TITLE
Export Survey Result To Csv In Persian Show unusual character

### ISSUE THREAD

**Issue by behzadvahidpour** [DNNCommunity/DNN.Survey#61]
Export Survey Result To Csv In Persian Show unusual character

- DNN: 09.06.01
- Module: 09.01.00

1. Add Survey with Answers in Persian Lag 
2. Try To export Result To CSV

![Survey](https://user-images.githubusercontent.com/13286513/118471537-1ccc0780-b71d-11eb-97fb-81ca6ccbd848.jpg)
[Survey_Results_1166_1400-02-27-022054.zip](https://github.com/DNNCommunity/DNN.Survey/files/6493044/Survey_Results_1166_1400-02-27-022054.zip)

**Comment by MaiklT** [comment]
As this is not really readable to me (and Persian characters are unusual in my culture, so I don't know which characters are unusual), I guess this is the behaviour that Excel always opens CSV files as ANSI encoded, but they are UTF-8 encoded when they come from the web.

Try the following: Open the CSV file with an editor, that is able to change the encoding (e.g. Notepad++), and change the encoding to ANSI. Then save the file, and try to open it with Excel again. That should do it.

**Comment by MaiklT** [comment]
As there was no answer to this in the last 6 months, I close this issue assuming that the answer above was correct.
