### ISSUE TITLE
Bug/feature?  View survey results when there are no responses

### ISSUE THREAD

**Issue by budhoward** [DNNCommunity/DNN.Survey#62]
When you click on "view results" before there are any surveys submitted, you get a critical error message.

Not sure if that's a defect, or if I should ask for a feature of either displaying a message that there are no results yet, or disable button until there are results.

**Comment by MaiklT** [comment]
[View Results] and [Export survey results to CSV] buttons will be hidden and the [View Results] option will be removed from module action menu when no answers are submitted.
