### ISSUE TITLE
Cannot give a custom name to the Survey results page

### ISSUE THREAD

**Issue by meffj00** [DNNCommunity/DNN.Survey#63]
I want to give the title 'DNN Survey Results' a custom name (not the standard name), but that look impossible. 
Am i missing something?

![SnipImage (002)](https://user-images.githubusercontent.com/12089564/204309188-a328c911-7df1-4592-9268-7704c09bc07a.JPG)

**Comment by MaiklT** [comment]
To quickly fix this you could add an entry in the file SurveyResults.ascx.resx (in App_LocalResource) with the key "ControlTitle_surveyresults.Text" and the value you want.

I will include this key in the next version, so you should create a resx file for your portal (SurveyResults.ascx.Portal-n.resx, where n = PortalID) or host (SurveyResults.ascx.Host.resx) - just copy the file SurveyResults.ascx.resx and give the copy that name.

**Comment by meffj00** [comment]
Ok, that looks good. Thanks!
