### ISSUE TITLE
The Survey module doesn't create a 'donuts' chart

### ISSUE THREAD

**Issue by meffj00** [DNNCommunity/DNN.Survey#64]
I have created a survey and want to display the free text answers in a donut chart. 
When testing with 4 participants, a 'doughnut' graph was neatly displayed, but things go wrong with even more participants!
But the module does not show a graph but puts the texts one after the other. The last line is rendered corrupted!
Can i do something about this?

![SnipImage (003)](https://user-images.githubusercontent.com/12089564/204311412-424a4859-e994-44ed-b723-c43e79ce8d50.JPG)

**Comment by MaiklT** [comment]
A chart seems not to be a good idea for a free text answer. I will think about an alternative.

**Comment by MaiklT** [comment]
A chart seems not to be a practicable presentation for a free text answer.

I'll add a new "Chart Type" calles "List", which will represent the answers like:

- Answer (Number of Votes)
- ...

or in a table.

If the type is free text answer, only this chart type is possible (and reasonable).

**Comment by meffj00** [comment]
Ok, that looks good to me. Thanks!
