### ISSUE TITLE
Starttext of a sentence not displayed

### ISSUE THREAD

**Issue by meffj00** [DNNCommunity/DNN.Survey#65]
Starttext of a sentence not displayed (Horizontal Bar).
If you chosse for a 'Bar' chart the all answers shown together.
In short, whatever graph you choose, it doesn't look good!

![SnipImage (006)](https://user-images.githubusercontent.com/12089564/204312651-f5e034b2-8948-465b-95c9-23d21044e44f.JPG)

**Comment by MaiklT** [comment]
A chart seems not to be a good idea for a free text answer. I will think about an alternative.
